import type { ReactNode } from "react";
import { AnimatedStatValue } from "../components/AnimatedStatValue";

const instagramDmUrl = "https://www.instagram.com/direct/t/britishturks";

// Update these numbers once; both insight sections use the same source.
const insights = [
  { value: 133, suffix: "K+", label: "Instagram followers" },
  { value: 6.4, suffix: "M+", decimals: 1, label: "Recent views" },
  { value: 2.1, suffix: "M+", decimals: 1, label: "Accounts reached" },
  { value: 241, suffix: "K+", label: "Interactions" },
  { value: 69.9, suffix: "%", decimals: 1, label: "Views from non-followers" },
  { value: 85.5, suffix: "%", decimals: 1, label: "Views generated by Reels" }
];

const reelsInsight = insights[5];

const packages = [
  {
    name: "Just Story Package",
    price: "£250",
    bestFor: "Quick announcements, event reminders and link pushes",
    features: [
      "5 Instagram Stories",
      "Link sticker where available",
      "Account tag",
      "Ideal for short-term visibility",
      "Instagram DM booking"
    ]
  },
  {
    name: "Starter Package",
    price: "£300",
    bestFor: "First-time advertisers and small businesses",
    features: [
      "1 Instagram Post or Reel",
      "2 Instagram Stories",
      "Account tag",
      "Campaign CTA support",
      "Instagram DM booking"
    ]
  },
  {
    name: "Standard Package",
    price: "£450",
    bestFor: "Single campaign promotion",
    features: [
      "1 Instagram Post or Reel",
      "3 Instagram Stories",
      "Pinned post for 3 days",
      "Profile link placement for 3 days",
      "Basic performance summary",
      "Instagram DM booking"
    ]
  },
  {
    name: "Advantage Package",
    price: "£600",
    label: "Most Popular",
    bestFor: "Businesses wanting stronger visibility",
    features: [
      "2 Instagram Posts or Reels",
      "4 Instagram Stories",
      "Pinned post for 7 days",
      "Profile link placement for 7 days",
      "Cross-share to other BritishTurks platforms where suitable",
      "Basic campaign performance summary",
      "Instagram DM booking"
    ]
  },
  {
    name: "Pro Support Package",
    price: "£800",
    bestFor: "Brands needing campaign support",
    features: [
      "2 Instagram Posts or Reels",
      "5 Instagram Stories",
      "Campaign strategy support",
      "Caption and CTA optimisation",
      "Community engagement support",
      "Profile link placement for 7 days",
      "Basic performance summary",
      "Instagram DM booking"
    ]
  },
  {
    name: "Premium Video Invitation Package",
    price: "From £1,250",
    bestFor: "Restaurants, events, clinics, services and business launches",
    features: [
      "Promotional video or interview-style shoot",
      "Edited Instagram Reel",
      "3 Instagram Stories",
      "Pinned post",
      "Profile link placement",
      "Cross-platform sharing where suitable",
      "Price may vary depending on location, filming duration and editing requirements",
      "Instagram DM booking"
    ]
  }
];

const reasons = [
  "Trusted UK Turkish community platform",
  "Strong Instagram Reels performance",
  "High non-follower reach",
  "Community-focused content",
  "Ideal for brands targeting Turkish-speaking audiences in the UK",
  "Suitable for events, restaurants, clinics, legal services, travel, finance, property and local businesses"
];

const faqs = [
  {
    question: "Do I pay online?",
    answer:
      "No. Please contact us on Instagram DM to discuss availability, campaign details and payment options."
  },
  {
    question: "Can you guarantee sales?",
    answer:
      "No. We do not guarantee sales or leads. Our packages are designed to increase brand visibility and reach within the UK Turkish community."
  },
  {
    question: "Can I choose the posting date?",
    answer: "Yes, subject to availability and editorial schedule."
  },
  {
    question: "Can you create the content for us?",
    answer:
      "Yes. We can support with captions, CTA wording and selected campaign formats. Video production is available under the Premium Video Invitation Package."
  },
  {
    question: "Will the post be marked as sponsored?",
    answer:
      "Yes. Sponsored content will be clearly disclosed in line with UK advertising guidelines."
  }
];

function CtaButton({
  children,
  variant = "primary",
  className = ""
}: {
  children: ReactNode;
  variant?: "primary" | "secondary";
  className?: string;
}) {
  const styles =
    variant === "primary"
      ? "bg-white text-midnight shadow-glow hover:-translate-y-0.5 hover:bg-gold"
      : "border border-white/15 bg-white/5 text-white hover:-translate-y-0.5 hover:border-white/35 hover:bg-white/10";

  return (
    <a
      href={instagramDmUrl}
      target="_blank"
      rel="noopener noreferrer"
      className={`inline-flex min-h-12 items-center justify-center rounded-full px-6 text-sm font-bold transition duration-300 ${styles} ${className}`}
    >
      {children}
    </a>
  );
}

function SectionHeader({
  eyebrow,
  title,
  text
}: {
  eyebrow: string;
  title: string;
  text?: string;
}) {
  return (
    <div className="mx-auto mb-10 max-w-3xl text-center">
      <p className="mb-3 text-sm font-bold uppercase tracking-[0.22em] text-gold">{eyebrow}</p>
      <h2 className="text-3xl font-black tracking-tight text-white sm:text-4xl">{title}</h2>
      {text ? <p className="mt-4 text-base leading-7 text-slate-300 sm:text-lg">{text}</p> : null}
    </div>
  );
}

function CheckMark() {
  return (
    <span className="mt-1 inline-flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-royal/20 text-xs font-black text-gold">
      ✓
    </span>
  );
}

export default function Home() {
  return (
    <main className="overflow-hidden text-white">
      <section className="premium-grid relative min-h-screen px-5 py-6 sm:px-8 lg:px-12">
        <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_50%_0%,rgba(109,93,252,0.28),transparent_42rem)]" />
        <nav className="mx-auto flex max-w-7xl items-center justify-between gap-4 rounded-full border border-white/10 bg-white/[0.04] px-4 py-3 backdrop-blur-xl sm:px-6">
          <a href="#top" className="flex items-center gap-3" aria-label="BritishTurks home">
            <span className="flex h-10 w-10 items-center justify-center rounded-full bg-white text-sm font-black text-midnight">
              BT
            </span>
            <span>
              <span className="block text-sm font-black tracking-wide">BritishTurks</span>
              <span className="block text-xs text-slate-400">@britishturks</span>
            </span>
          </a>
          <div className="hidden items-center gap-7 text-sm font-semibold text-slate-300 md:flex">
            <a className="transition hover:text-white" href="#packages">
              Packages
            </a>
            <a className="transition hover:text-white" href="#insights">
              Insights
            </a>
            <a className="transition hover:text-white" href="#faq">
              FAQ
            </a>
          </div>
          <CtaButton className="hidden sm:inline-flex">Send DM on Instagram</CtaButton>
        </nav>

        <div id="top" className="mx-auto grid max-w-7xl items-center gap-12 pb-14 pt-16 lg:grid-cols-[1.05fr_0.95fr] lg:pb-24 lg:pt-24">
          <div>
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.06] px-4 py-2 text-sm font-semibold text-slate-200">
              <span className="h-2 w-2 rounded-full bg-gold shadow-[0_0_18px_rgba(247,201,107,0.8)]" />
              UK Turkish Community Media Platform
            </div>
            <h1 className="max-w-5xl text-5xl font-black tracking-tight text-white sm:text-6xl lg:text-7xl">
              Advertise with BritishTurks
            </h1>
            <p className="mt-6 max-w-2xl text-xl font-semibold leading-8 text-slate-200 sm:text-2xl">
              Reach the UK Turkish community through one of Britain&apos;s most trusted Turkish media platforms.
            </p>
            <p className="mt-5 max-w-2xl text-base leading-8 text-slate-300 sm:text-lg">
              BritishTurks helps brands, events and businesses promote their services through high-performing Instagram
              Reels, Stories and community-focused content.
            </p>
            <div className="mt-9 flex flex-col gap-3 sm:flex-row">
              <CtaButton>Send DM on Instagram</CtaButton>
              <a
                href="#packages"
                className="inline-flex min-h-12 items-center justify-center rounded-full border border-white/15 bg-white/5 px-6 text-sm font-bold text-white transition duration-300 hover:-translate-y-0.5 hover:border-white/35 hover:bg-white/10"
              >
                View Packages
              </a>
            </div>
          </div>

          <div className="glass-panel gradient-border rounded-[2rem] p-5 sm:p-7">
            <div className="rounded-[1.5rem] border border-white/10 bg-ink/70 p-5 sm:p-6">
              <div className="mb-6 flex items-center justify-between gap-4">
                <div>
                  <p className="text-sm font-semibold text-slate-400">Media kit preview</p>
                  <h2 className="mt-1 text-2xl font-black">BritishTurks reach</h2>
                </div>
                <span className="rounded-full bg-gold px-3 py-1 text-xs font-black uppercase tracking-wide text-midnight">
                  2026
                </span>
              </div>
              <div className="grid gap-3 sm:grid-cols-2">
                {insights.slice(0, 4).map((item) => (
                  <div key={item.label} className="rounded-2xl border border-white/10 bg-white/[0.05] p-4">
                    <AnimatedStatValue
                      value={item.value}
                      suffix={item.suffix}
                      decimals={item.decimals}
                      className="text-3xl font-black text-white"
                    />
                    <p className="mt-1 text-sm leading-5 text-slate-400">{item.label}</p>
                  </div>
                ))}
              </div>
              <div className="mt-4 rounded-2xl bg-gradient-to-br from-royal/35 to-violet/25 p-4">
                <div className="flex items-end justify-between gap-4">
                  <div>
                    <p className="text-sm font-semibold text-slate-200">Reels-led discovery</p>
                    <AnimatedStatValue
                      value={reelsInsight.value}
                      suffix={reelsInsight.suffix}
                      decimals={reelsInsight.decimals}
                      className="mt-1 block text-4xl font-black"
                    />
                  </div>
                  <div className="flex h-20 items-end gap-2">
                    {[38, 52, 46, 68, 84].map((height) => (
                      <span
                        key={height}
                        className="w-6 rounded-t-full bg-white/80"
                        style={{ height: `${height}%` }}
                      />
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section id="insights" className="px-5 py-20 sm:px-8 lg:px-12">
        <div className="mx-auto max-w-7xl">
          <SectionHeader
            eyebrow="Account insights"
            title="Built for visibility inside a focused community"
            text="Recent Instagram performance gives advertisers a strong route into Turkish-speaking audiences across the UK."
          />
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {insights.map((item) => (
              <div
                key={item.label}
                className="rounded-3xl border border-white/10 bg-white/[0.045] p-6 transition duration-300 hover:-translate-y-1 hover:border-white/20 hover:bg-white/[0.07]"
              >
                <AnimatedStatValue
                  value={item.value}
                  suffix={item.suffix}
                  decimals={item.decimals}
                  className="block text-4xl font-black tracking-tight text-white"
                />
                <p className="mt-2 text-sm font-semibold uppercase tracking-[0.16em] text-slate-400">{item.label}</p>
              </div>
            ))}
          </div>
          <p className="mt-5 text-center text-sm text-slate-500">
            Figures are based on recent Instagram account insights and may vary by campaign period.
          </p>
        </div>
      </section>

      <section id="packages" className="px-5 py-20 sm:px-8 lg:px-12">
        <div className="mx-auto max-w-7xl">
          <SectionHeader
            eyebrow="Advertising packages"
            title="Choose the visibility level that fits your campaign"
            text="Simple Instagram advertising options for launches, events, services, offers and long-term brand awareness."
          />
          <div className="grid gap-5 lg:grid-cols-3">
            {packages.map((item) => (
              <article
                key={item.name}
                className={`relative flex rounded-3xl border p-6 transition duration-300 hover:-translate-y-1 ${
                  item.label
                    ? "border-gold/45 bg-gradient-to-br from-white/[0.12] to-royal/15 shadow-glow"
                    : "border-white/10 bg-white/[0.045] hover:border-white/20 hover:bg-white/[0.07]"
                }`}
              >
                {item.label ? (
                  <span className="absolute right-5 top-5 rounded-full bg-gold px-3 py-1 text-xs font-black uppercase tracking-wide text-midnight">
                    {item.label}
                  </span>
                ) : null}
                <div className="flex min-h-full w-full flex-col">
                  <div className="pr-24">
                    <h3 className="text-2xl font-black tracking-tight">{item.name}</h3>
                    <p className="mt-4 text-4xl font-black text-white">{item.price}</p>
                  </div>
                  <p className="mt-4 min-h-14 text-sm font-semibold leading-6 text-slate-300">
                    <span className="text-slate-500">Best for: </span>
                    {item.bestFor}
                  </p>
                  <ul className="mt-6 space-y-3">
                    {item.features.map((feature) => (
                      <li key={feature} className="flex gap-3 text-sm leading-6 text-slate-300">
                        <CheckMark />
                        <span>{feature}</span>
                      </li>
                    ))}
                  </ul>
                  <CtaButton className="mt-7 w-full">Buy Package</CtaButton>
                </div>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section className="px-5 py-16 sm:px-8 lg:px-12">
        <div className="mx-auto max-w-7xl rounded-[2rem] border border-white/10 bg-gradient-to-br from-white/[0.1] via-royal/15 to-violet/10 p-8 shadow-premium sm:p-10 lg:flex lg:items-center lg:justify-between lg:gap-10">
          <div className="max-w-3xl">
            <p className="mb-3 text-sm font-bold uppercase tracking-[0.22em] text-gold">Custom campaigns</p>
            <h2 className="text-3xl font-black tracking-tight sm:text-4xl">Need a monthly campaign?</h2>
            <p className="mt-4 text-base leading-8 text-slate-300 sm:text-lg">
              For long-term visibility, restaurant launches, events, clinics, legal services, estate agents or brand
              partnerships, we can create a custom monthly campaign.
            </p>
          </div>
          <CtaButton className="mt-7 shrink-0 lg:mt-0">Discuss on Instagram</CtaButton>
        </div>
      </section>

      <section className="px-5 py-20 sm:px-8 lg:px-12">
        <div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.82fr_1.18fr] lg:items-start">
          <div>
            <p className="mb-3 text-sm font-bold uppercase tracking-[0.22em] text-gold">Why BritishTurks?</p>
            <h2 className="text-3xl font-black tracking-tight sm:text-4xl">Why advertise with BritishTurks?</h2>
            <p className="mt-4 text-base leading-8 text-slate-300">
              A trusted media platform for brands that want audience fit, cultural relevance and strong Instagram reach.
            </p>
          </div>
          <div className="grid gap-4 sm:grid-cols-2">
            {reasons.map((reason) => (
              <div key={reason} className="rounded-3xl border border-white/10 bg-white/[0.045] p-5">
                <div className="flex gap-3 text-sm font-semibold leading-6 text-slate-200">
                  <CheckMark />
                  <span>{reason}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="px-5 py-10 sm:px-8 lg:px-12">
        <div className="mx-auto max-w-5xl rounded-3xl border border-gold/25 bg-gold/10 p-6 text-sm leading-7 text-slate-200 sm:p-8">
          <strong className="text-white">Advertising disclosure: </strong>
          All sponsored content will be clearly disclosed in line with UK advertising guidelines. BritishTurks does not
          guarantee sales, leads or specific results. Campaign performance may vary depending on content, timing,
          audience interest and platform algorithms.
        </div>
      </section>

      <section id="faq" className="px-5 py-20 sm:px-8 lg:px-12">
        <div className="mx-auto max-w-4xl">
          <SectionHeader eyebrow="FAQ" title="Common questions before you book" />
          <div className="space-y-4">
            {faqs.map((faq) => (
              <details
                key={faq.question}
                className="group rounded-3xl border border-white/10 bg-white/[0.045] p-6 open:bg-white/[0.07]"
              >
                <summary className="flex cursor-pointer list-none items-center justify-between gap-5 text-left text-lg font-black text-white">
                  {faq.question}
                  <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-white/10 text-xl transition group-open:rotate-45">
                    +
                  </span>
                </summary>
                <p className="mt-4 text-sm leading-7 text-slate-300">{faq.answer}</p>
              </details>
            ))}
          </div>
        </div>
      </section>

      <section className="sticky bottom-0 z-20 border-t border-white/10 bg-ink/85 px-5 py-3 backdrop-blur-xl sm:px-8">
        <div className="mx-auto flex max-w-7xl flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <p className="text-sm font-semibold text-slate-300">
            Ready to promote your brand to the UK Turkish community?
          </p>
          <CtaButton className="w-full sm:w-auto">Send DM on Instagram</CtaButton>
        </div>
      </section>

      <footer className="px-5 py-12 sm:px-8 lg:px-12">
        <div className="mx-auto flex max-w-7xl flex-col gap-6 border-t border-white/10 pt-8 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <p className="text-xl font-black">BritishTurks</p>
            <p className="mt-1 text-sm text-slate-400">UK Turkish Community Media Platform</p>
            <p className="mt-2 text-sm font-semibold text-slate-300">Instagram: @britishturks</p>
          </div>
          <CtaButton>Send DM on Instagram</CtaButton>
        </div>
      </footer>
    </main>
  );
}
