export type Locale = 'en' | 'tr';

const englishInsights = [{ value: 133, suffix: 'K+', label: 'Instagram followers' }, { value: 6.4, suffix: 'M+', decimals: 1, label: 'Recent views' }, { value: 2.1, suffix: 'M+', decimals: 1, label: 'Accounts reached' }, { value: 241, suffix: 'K+', label: 'Interactions' }, { value: 69.9, suffix: '%', decimals: 1, label: 'Views from non-followers' }, { value: 85.5, suffix: '%', decimals: 1, label: 'Views generated by Reels' }];

const turkishInsights = [{ value: 133, suffix: 'K+', label: 'Instagram takipçisi' }, { value: 6.4, suffix: 'M+', decimals: 1, label: 'Son görüntülenme' }, { value: 2.1, suffix: 'M+', decimals: 1, label: 'Ulaşılan hesap' }, { value: 241, suffix: 'K+', label: 'Etkileşim' }, { value: 69.9, suffix: '%', decimals: 1, label: 'Takipçi olmayanlardan gelen görüntülenme' }, { value: 85.5, suffix: '%', decimals: 1, label: 'Görüntülemelerin Reels kaynaklı oranı' }];

const siteContentData = {
  en: {
    locale: 'en',
    alternate: { href: '/tr', label: 'Türkçe', ariaLabel: 'View the Turkish version' },
    nav: { packages: 'Packages', insights: 'Insights', faq: 'FAQ', cta: 'Send DM on Instagram' },
    hero: {
      eyebrow: 'UK Turkish Community Media Platform',
      title: 'Advertise with BritishTurks',
      subtitle: `Reach the UK Turkish community through one of Britain's most trusted Turkish media platforms.`,
      supportingText: 'BritishTurks helps brands, events and businesses promote their services through high-performing Instagram Reels, Stories and community-focused content.',
      primaryCta: 'Send DM on Instagram',
      secondaryCta: 'View Packages',
      mediaKitLabel: 'Media kit preview',
      reachTitle: 'BritishTurks reach',
      year: '2026',
      reelsTitle: 'Reels-led discovery'
    },
    insights: {
      eyebrow: 'Account insights',
      title: 'Built for visibility inside a focused community',
      text: 'Recent Instagram performance gives advertisers a strong route into Turkish-speaking audiences across the UK.',
      disclaimer: 'Figures are based on recent Instagram account insights and may vary by campaign period.',
      items: englishInsights
    },
    packages: {
      eyebrow: 'Advertising packages',
      title: 'Choose the visibility level that fits your campaign',
      text: 'Simple Instagram advertising options for launches, events, services, offers and long-term brand awareness.',
      bestForLabel: 'Best for:',
      buyCta: 'Buy Package',
      items: [
        { name: 'Just Story Package', price: '£250', bestFor: 'Quick announcements, event reminders and story-led link pushes', features: ['5 x Instagram Stories with Link and Tag'] },
        { name: 'Starter Package', price: '£300', bestFor: 'First-time advertisers and small businesses', features: ['1 x Instagram Post (Feed or Reels)', '2 x Instagram Stories (Link and Tag)', '1 x Pinned Post for 3 Days', '5% Discount on Second Order (Valid for 3 Months)'] },
        { name: 'Standard Package', price: '£450', bestFor: 'Single campaign promotion', features: ['1 x Instagram Post (Feed or Reels)', '3 x Instagram Stories (Link and Tag)', '1 x Pinned Post for 3 Days', '1 x Website Link on Profile (for 3 Days)', '10% Discount on Second Order (Valid for 3 Months)'] },
        { name: 'Advantage Package', price: '£600', label: 'Most Popular', bestFor: 'Businesses wanting stronger visibility', features: ['2 x Instagram Posts (Feed or Reels)', '4 x Instagram Stories (Link and Tag)', '1 x Pinned Post for 7 Days', '1 x Website Link on Profile (for 7 Days)', '1 x Cross-Sharing to All Platforms', 'Bonus: 10% Discount on a Custom Add-on', '20% Discount on Second Order (Valid for 3 Months)'] },
        { name: 'Pro Support Package', price: '£800', bestFor: 'Brands needing campaign support', features: ['2 x Instagram Posts (Feed or Reels)', '4 x Instagram Stories (Link and Tag)', '1 x Pinned Post for 7 Days', '1 x Website Link on Profile (for 7 Days)', '1 x Cross-Sharing to All Platforms', '1 x Instagram Account Follow-Back Service (for 60 Days)', '3 x Engaging Comments on Your Instagram Posts', '1 x Story Added to Instagram Highlights (for 30 Days)', '20% Discount on Second Order (Valid for 3 Months)'] },
        { name: 'Premium Video Invitation Package', price: '£1,250', bestFor: 'Restaurants, events, clinics, services and business launches', features: ['1 x Interview or Promotional Video Shoot', '1 x Reel Video', '3 x Instagram Stories (Link and Tag)', '1 x Pinned Post for 7 Days', '1 x Website Link on Profile (for 7 Days)', '1 x Cross-Sharing to All Platforms', '1 x Instagram Account Follow-Back Service (for 60 Days)', '3 x Engaging Comments on Your Instagram Posts', '1 x Story Added to Instagram Highlights (for 30 Days)'] }
      ],
      addOns: {
        title: 'Optional Add-Ons',
        items: ['Graphic Design: starting from £150', 'Video Design (Reels, Animation, Promotional): starting from £250'],
        note: 'These services are charged separately if requested.',
        flexibleTitle: 'Flexible Package Options',
        flexibleText: [`We can prepare a custom package and pricing tailored to your company's needs.`, 'If none of the existing packages fit perfectly, we can craft a bespoke solution together.']
      }
    },
    custom: { eyebrow: 'Custom campaigns', title: 'Need a monthly campaign?', text: 'For long-term visibility, restaurant launches, events, clinics, legal services, estate agents or brand partnerships, we can create a custom monthly campaign.', cta: 'Discuss on Instagram' },
    why: {
      eyebrow: 'Why BritishTurks?',
      title: 'Why advertise with BritishTurks?',
      text: 'A trusted media platform for brands that want audience fit, cultural relevance and strong Instagram reach.',
      points: ['Trusted UK Turkish community platform', 'Strong Instagram Reels performance', 'High non-follower reach', 'Community-focused content', 'Ideal for brands targeting Turkish-speaking audiences in the UK', 'Suitable for events, restaurants, clinics, legal services, travel, finance, property and local businesses']
    },
    disclosure: { prefix: 'Advertising disclosure: ', text: 'All sponsored content will be clearly disclosed in line with UK advertising guidelines. BritishTurks does not guarantee sales, leads or specific results. Campaign performance may vary depending on content, timing, audience interest and platform algorithms.' },
    faq: {
      eyebrow: 'FAQ',
      title: 'Common questions before you book',
      items: [
        { question: 'Do I pay online?', answer: 'No. Please contact us on Instagram DM to discuss availability, campaign details and payment options.' },
        { question: 'Can you guarantee sales?', answer: 'No. We do not guarantee sales or leads. Our packages are designed to increase brand visibility and reach within the UK Turkish community.' },
        { question: 'Can I choose the posting date?', answer: 'Yes, subject to availability and editorial schedule.' },
        { question: 'Can you create the content for us?', answer: 'Yes. We can support with captions, CTA wording and selected campaign formats. Video production is available under the Premium Video Invitation Package.' },
        { question: 'Will the post be marked as sponsored?', answer: 'Yes. Sponsored content will be clearly disclosed in line with UK advertising guidelines.' }
      ]
    },
    sticky: { text: 'Ready to promote your brand to the UK Turkish community?', cta: 'Send DM on Instagram' },
    footer: { brand: 'BritishTurks', description: 'UK Turkish Community Media Platform', instagram: 'Instagram: @britishturks', cta: 'Send DM on Instagram' }
  },
  tr: {
    locale: 'tr',
    alternate: { href: '/', label: 'English', ariaLabel: 'İngilizce sürümü görüntüle' },
    nav: { packages: 'Paketler', insights: 'İstatistikler', faq: 'SSS', cta: `Instagram'dan DM gönder` },
    hero: {
      eyebrow: 'Birleşik Krallık Türk Toplumu Medya Platformu',
      title: 'BritishTurks ile reklam verin',
      subtitle: `Britanya'nın en güvenilir Türk medya platformlarından biri üzerinden Birleşik Krallık'taki Türk toplumuna ulaşın.`,
      supportingText: 'BritishTurks; markaların, etkinliklerin ve işletmelerin hizmetlerini yüksek performanslı Instagram Reels, Story ve topluluk odaklı içeriklerle tanıtmasına yardımcı olur.',
      primaryCta: `Instagram'dan DM gönder`,
      secondaryCta: 'Paketleri Gör',
      mediaKitLabel: 'Medya kiti önizlemesi',
      reachTitle: 'BritishTurks erişimi',
      year: '2026',
      reelsTitle: 'Reels odaklı keşif'
    },
    insights: {
      eyebrow: 'Hesap istatistikleri',
      title: 'Odaklı bir topluluk içinde görünürlük için tasarlandı',
      text: `Güncel Instagram performansı, reklamverenlere Birleşik Krallık'taki Türkçe konuşan kitlelere ulaşmak için güçlü bir kanal sunar.`,
      disclaimer: 'Rakamlar yakın dönem Instagram hesap istatistiklerine dayanır ve kampanya dönemine göre değişebilir.',
      items: turkishInsights
    },
    packages: {
      eyebrow: 'Reklam paketleri',
      title: 'Kampanyanıza uygun görünürlük seviyesini seçin',
      text: 'Lansmanlar, etkinlikler, hizmetler, kampanyalar ve uzun vadeli marka bilinirliği için sade Instagram reklam seçenekleri.',
      bestForLabel: 'En uygun:',
      buyCta: 'Paketi Al',
      items: [
        { name: 'Sadece Story Paketi', price: '£250', bestFor: 'Hızlı duyurular, etkinlik hatırlatmaları ve Story üzerinden link yönlendirmeleri', features: ['5 x Instagram Story (Link ve Etiket ile)'] },
        { name: 'Başlangıç Paketi', price: '£300', bestFor: 'İlk kez reklam verenler ve küçük işletmeler', features: ['1 x Instagram gönderisi (Feed veya Reels)', '2 x Instagram Story (Link ve Etiket ile)', '1 x 3 gün sabitlenmiş gönderi', 'İkinci siparişte %5 indirim (3 ay geçerli)'] },
        { name: 'Standart Paket', price: '£450', bestFor: 'Tek kampanya tanıtımı', features: ['1 x Instagram gönderisi (Feed veya Reels)', '3 x Instagram Story (Link ve Etiket ile)', '1 x 3 gün sabitlenmiş gönderi', '1 x profilde website linki (3 gün)', 'İkinci siparişte %10 indirim (3 ay geçerli)'] },
        { name: 'Avantaj Paketi', price: '£600', label: 'En Popüler', bestFor: 'Daha güçlü görünürlük isteyen işletmeler', features: ['2 x Instagram gönderisi (Feed veya Reels)', '4 x Instagram Story (Link ve Etiket ile)', '1 x 7 gün sabitlenmiş gönderi', '1 x profilde website linki (7 gün)', '1 x tüm platformlarda çapraz paylaşım', 'Bonus: özel ek hizmette %10 indirim', 'İkinci siparişte %20 indirim (3 ay geçerli)'] },
        { name: 'Pro Destek Paketi', price: '£800', bestFor: 'Kampanya desteğine ihtiyaç duyan markalar', features: ['2 x Instagram gönderisi (Feed veya Reels)', '4 x Instagram Story (Link ve Etiket ile)', '1 x 7 gün sabitlenmiş gönderi', '1 x profilde website linki (7 gün)', '1 x tüm platformlarda çapraz paylaşım', '1 x Instagram hesap follow-back servisi (60 gün)', 'Instagram gönderilerinize 3 x etkileşim yorumu', `1 x Instagram Highlights'a Story ekleme (30 gün)`, 'İkinci siparişte %20 indirim (3 ay geçerli)'] },
        { name: 'Premium Video Davet Paketi', price: '£1,250', bestFor: 'Restoranlar, etkinlikler, klinikler, hizmetler ve işletme lansmanları', features: ['1 x röportaj veya tanıtım videosu çekimi', '1 x Reel videosu', '3 x Instagram Story (Link ve Etiket ile)', '1 x 7 gün sabitlenmiş gönderi', '1 x profilde website linki (7 gün)', '1 x tüm platformlarda çapraz paylaşım', '1 x Instagram hesap follow-back servisi (60 gün)', 'Instagram gönderilerinize 3 x etkileşim yorumu', `1 x Instagram Highlights'a Story ekleme (30 gün)`] }
      ],
      addOns: {
        title: 'Opsiyonel Ek Hizmetler',
        items: [`Grafik tasarım: £150'den başlayan fiyatlarla`, `Video tasarım (Reels, animasyon, tanıtım): £250'den başlayan fiyatlarla`],
        note: 'Bu hizmetler talep edilirse ayrıca ücretlendirilir.',
        flexibleTitle: 'Esnek Paket Seçenekleri',
        flexibleText: ['Şirketinizin ihtiyacına göre özel paket ve fiyatlandırma hazırlayabiliriz.', 'Mevcut paketlerden hiçbiri tam uygun değilse size özel bir çözüm oluşturabiliriz.']
      }
    },
    custom: { eyebrow: 'Özel kampanyalar', title: 'Aylık kampanyaya mı ihtiyacınız var?', text: 'Uzun vadeli görünürlük, restoran lansmanları, etkinlikler, klinikler, hukuk hizmetleri, emlak danışmanları veya marka iş birlikleri için özel bir aylık kampanya oluşturabiliriz.', cta: `Instagram'da konuşalım` },
    why: {
      eyebrow: 'Neden BritishTurks?',
      title: 'BritishTurks ile neden reklam vermelisiniz?',
      text: 'Kitle uyumu, kültürel yakınlık ve güçlü Instagram erişimi isteyen markalar için güvenilir bir medya platformu.',
      points: ['Güvenilir UK Türk toplumu platformu', 'Güçlü Instagram Reels performansı', 'Yüksek takipçi dışı erişim', 'Topluluk odaklı içerik', `Birleşik Krallık'taki Türkçe konuşan kitleleri hedefleyen markalar için ideal`, 'Etkinlikler, restoranlar, klinikler, hukuk hizmetleri, seyahat, finans, emlak ve yerel işletmeler için uygun']
    },
    disclosure: { prefix: 'Reklam açıklaması: ', text: 'Tüm sponsorlu içerikler UK reklam yönergelerine uygun şekilde açıkça belirtilecektir. BritishTurks satış, potansiyel müşteri veya belirli sonuç garantisi vermez. Kampanya performansı içerik, zamanlama, kitle ilgisi ve platform algoritmalarına göre değişebilir.' },
    faq: {
      eyebrow: 'SSS',
      title: 'Rezervasyon öncesi sık sorulan sorular',
      items: [
        { question: 'Online ödeme yapıyor muyum?', answer: 'Hayır. Uygunluk, kampanya detayları ve ödeme seçeneklerini konuşmak için lütfen Instagram DM üzerinden iletişime geçin.' },
        { question: 'Satış garantisi veriyor musunuz?', answer: 'Hayır. Satış veya potansiyel müşteri garantisi vermiyoruz. Paketlerimiz, UK Türk toplumu içinde marka görünürlüğünü ve erişimi artırmak için tasarlanmıştır.' },
        { question: 'Paylaşım tarihini seçebilir miyim?', answer: 'Evet, uygunluk ve editoryal takvime bağlıdır.' },
        { question: 'İçeriği bizim için hazırlayabilir misiniz?', answer: 'Evet. Metin, CTA dili ve seçili kampanya formatlarında destek olabiliriz. Video prodüksiyonu Premium Video Davet Paketi kapsamında sunulur.' },
        { question: 'Paylaşım sponsorlu olarak işaretlenecek mi?', answer: 'Evet. Sponsorlu içerikler UK reklam yönergelerine uygun şekilde açıkça belirtilecektir.' }
      ]
    },
    sticky: { text: 'Markanızı Birleşik Krallık Türk toplumuna tanıtmaya hazır mısınız?', cta: `Instagram'dan DM gönder` },
    footer: { brand: 'BritishTurks', description: 'Birleşik Krallık Türk Toplumu Medya Platformu', instagram: 'Instagram: @britishturks', cta: `Instagram'dan DM gönder` }
  }
};

export type Insight = (typeof englishInsights)[number];
export type LandingPageContent = (typeof siteContentData)[Locale];
export const siteContent = siteContentData;
