export type Locale = "en" | "tr";

export type Insight = {
  value: number;
  suffix: string;
  decimals?: number;
  label: string;
};

type PackageItem = {
  name: string;
  price: string;
  label?: string;
  bestFor: string;
  features: string[];
};

export type LandingPageContent = {
  locale: Locale;
  alternate: {
    href: string;
    label: string;
    ariaLabel: string;
  };
  nav: {
    packages: string;
    insights: string;
    faq: string;
    cta: string;
  };
  hero: {
    eyebrow: string;
    title: string;
    subtitle: string;
    supportingText: string;
    primaryCta: string;
    secondaryCta: string;
    mediaKitLabel: string;
    reachTitle: string;
    year: string;
    reelsTitle: string;
  };
  insights: {
    eyebrow: string;
    title: string;
    text: string;
    disclaimer: string;
    items: Insight[];
  };
  packages: {
    eyebrow: string;
    title: string;
    text: string;
    bestForLabel: string;
    buyCta: string;
    items: PackageItem[];
  };
  custom: {
    eyebrow: string;
    title: string;
    text: string;
    cta: string;
  };
  why: {
    eyebrow: string;
    title: string;
    text: string;
    points: string[];
  };
  disclosure: {
    prefix: string;
    text: string;
  };
  faq: {
    eyebrow: string;
    title: string;
    items: Array<{
      question: string;
      answer: string;
    }>;
  };
  sticky: {
    text: string;
    cta: string;
  };
  footer: {
    brand: string;
    description: string;
    instagram: string;
    cta: string;
  };
};

const englishInsights: Insight[] = [
  { value: 133, suffix: "K+", label: "Instagram followers" },
  { value: 6.4, suffix: "M+", decimals: 1, label: "Recent views" },
  { value: 2.1, suffix: "M+", decimals: 1, label: "Accounts reached" },
  { value: 241, suffix: "K+", label: "Interactions" },
  { value: 69.9, suffix: "%", decimals: 1, label: "Views from non-followers" },
  { value: 85.5, suffix: "%", decimals: 1, label: "Views generated by Reels" }
];

const turkishInsights: Insight[] = [
  { value: 133, suffix: "K+", label: "Instagram takipçisi" },
  { value: 6.4, suffix: "M+", decimals: 1, label: "Son görüntülenme" },
  { value: 2.1, suffix: "M+", decimals: 1, label: "Ulaşılan hesap" },
  { value: 241, suffix: "K+", label: "Etkileşim" },
  { value: 69.9, suffix: "%", decimals: 1, label: "Takipçi olmayanlardan gelen görüntülenme" },
  { value: 85.5, suffix: "%", decimals: 1, label: "Görüntülemelerin Reels kaynaklı oranı" }
];

export const siteContent: Record<Locale, LandingPageContent> = {
  en: {
    locale: "en",
    alternate: {
      href: "/tr",
      label: "Türkçe",
      ariaLabel: "View the Turkish version"
    },
    nav: {
      packages: "Packages",
      insights: "Insights",
      faq: "FAQ",
      cta: "Send DM on Instagram"
    },
    hero: {
      eyebrow: "UK Turkish Community Media Platform",
      title: "Advertise with BritishTurks",
      subtitle: "Reach the UK Turkish community through one of Britain's most trusted Turkish media platforms.",
      supportingText:
        "BritishTurks helps brands, events and businesses promote their services through high-performing Instagram Reels, Stories and community-focused content.",
      primaryCta: "Send DM on Instagram",
      secondaryCta: "View Packages",
      mediaKitLabel: "Media kit preview",
      reachTitle: "BritishTurks reach",
      year: "2026",
      reelsTitle: "Reels-led discovery"
    },
    insights: {
      eyebrow: "Account insights",
      title: "Built for visibility inside a focused community",
      text:
        "Recent Instagram performance gives advertisers a strong route into Turkish-speaking audiences across the UK.",
      disclaimer: "Figures are based on recent Instagram account insights and may vary by campaign period.",
      items: englishInsights
    },
    packages: {
      eyebrow: "Advertising packages",
      title: "Choose the visibility level that fits your campaign",
      text: "Simple Instagram advertising options for launches, events, services, offers and long-term brand awareness.",
      bestForLabel: "Best for:",
      buyCta: "Buy Package",
      items: [
        {
          name: "Just Story Package",
          price: "£250",
          bestFor: "Quick announcements, event reminders and link pushes",
          features: [
            "5 Instagram Stories",
            "Link sticker where available",
            "Account tag",
            "Ideal for short-term visibility",
            "Instagram DM booking"
          ]
        },
        {
          name: "Starter Package",
          price: "£300",
          bestFor: "First-time advertisers and small businesses",
          features: [
            "1 Instagram Post or Reel",
            "2 Instagram Stories",
            "Account tag",
            "Campaign CTA support",
            "Instagram DM booking"
          ]
        },
        {
          name: "Standard Package",
          price: "£450",
          bestFor: "Single campaign promotion",
          features: [
            "1 Instagram Post or Reel",
            "3 Instagram Stories",
            "Pinned post for 3 days",
            "Profile link placement for 3 days",
            "Basic performance summary",
            "Instagram DM booking"
          ]
        },
        {
          name: "Advantage Package",
          price: "£600",
          label: "Most Popular",
          bestFor: "Businesses wanting stronger visibility",
          features: [
            "2 Instagram Posts or Reels",
            "4 Instagram Stories",
            "Pinned post for 7 days",
            "Profile link placement for 7 days",
            "Cross-share to other BritishTurks platforms where suitable",
            "Basic campaign performance summary",
            "Instagram DM booking"
          ]
        },
        {
          name: "Pro Support Package",
          price: "£800",
          bestFor: "Brands needing campaign support",
          features: [
            "2 Instagram Posts or Reels",
            "5 Instagram Stories",
            "Campaign strategy support",
            "Caption and CTA optimisation",
            "Community engagement support",
            "Profile link placement for 7 days",
            "Basic performance summary",
            "Instagram DM booking"
          ]
        },
        {
          name: "Premium Video Invitation Package",
          price: "From £1,250",
          bestFor: "Restaurants, events, clinics, services and business launches",
          features: [
            "Promotional video or interview-style shoot",
            "Edited Instagram Reel",
            "3 Instagram Stories",
            "Pinned post",
            "Profile link placement",
            "Cross-platform sharing where suitable",
            "Price may vary depending on location, filming duration and editing requirements",
            "Instagram DM booking"
          ]
        }
      ]
    },
    custom: {
      eyebrow: "Custom campaigns",
      title: "Need a monthly campaign?",
      text:
        "For long-term visibility, restaurant launches, events, clinics, legal services, estate agents or brand partnerships, we can create a custom monthly campaign.",
      cta: "Discuss on Instagram"
    },
    why: {
      eyebrow: "Why BritishTurks?",
      title: "Why advertise with BritishTurks?",
      text: "A trusted media platform for brands that want audience fit, cultural relevance and strong Instagram reach.",
      points: [
        "Trusted UK Turkish community platform",
        "Strong Instagram Reels performance",
        "High non-follower reach",
        "Community-focused content",
        "Ideal for brands targeting Turkish-speaking audiences in the UK",
        "Suitable for events, restaurants, clinics, legal services, travel, finance, property and local businesses"
      ]
    },
    disclosure: {
      prefix: "Advertising disclosure: ",
      text:
        "All sponsored content will be clearly disclosed in line with UK advertising guidelines. BritishTurks does not guarantee sales, leads or specific results. Campaign performance may vary depending on content, timing, audience interest and platform algorithms."
    },
    faq: {
      eyebrow: "FAQ",
      title: "Common questions before you book",
      items: [
        {
          question: "Do I pay online?",
          answer:
            "No. Please contact us on Instagram DM to discuss availability, campaign details and payment options."
        },
        {
          question: "Can you guarantee sales?",
          answer:
            "No. We do not guarantee sales or leads. Our packages are designed to increase brand visibility and reach within the UK Turkish community."
        },
        {
          question: "Can I choose the posting date?",
          answer: "Yes, subject to availability and editorial schedule."
        },
        {
          question: "Can you create the content for us?",
          answer:
            "Yes. We can support with captions, CTA wording and selected campaign formats. Video production is available under the Premium Video Invitation Package."
        },
        {
          question: "Will the post be marked as sponsored?",
          answer: "Yes. Sponsored content will be clearly disclosed in line with UK advertising guidelines."
        }
      ]
    },
    sticky: {
      text: "Ready to promote your brand to the UK Turkish community?",
      cta: "Send DM on Instagram"
    },
    footer: {
      brand: "BritishTurks",
      description: "UK Turkish Community Media Platform",
      instagram: "Instagram: @britishturks",
      cta: "Send DM on Instagram"
    }
  },
  tr: {
    locale: "tr",
    alternate: {
      href: "/",
      label: "English",
      ariaLabel: "İngilizce sürümü görüntüle"
    },
    nav: {
      packages: "Paketler",
      insights: "İstatistikler",
      faq: "SSS",
      cta: "Instagram'dan DM gönder"
    },
    hero: {
      eyebrow: "Birleşik Krallık Türk Toplumu Medya Platformu",
      title: "BritishTurks ile reklam verin",
      subtitle:
        "Britanya'nın en güvenilir Türk medya platformlarından biri üzerinden Birleşik Krallık'taki Türk toplumuna ulaşın.",
      supportingText:
        "BritishTurks; markaların, etkinliklerin ve işletmelerin hizmetlerini yüksek performanslı Instagram Reels, Story ve topluluk odaklı içeriklerle tanıtmasına yardımcı olur.",
      primaryCta: "Instagram'dan DM gönder",
      secondaryCta: "Paketleri Gör",
      mediaKitLabel: "Medya kiti önizlemesi",
      reachTitle: "BritishTurks erişimi",
      year: "2026",
      reelsTitle: "Reels odaklı keşif"
    },
    insights: {
      eyebrow: "Hesap istatistikleri",
      title: "Odaklı bir topluluk içinde görünürlük için tasarlandı",
      text:
        "Güncel Instagram performansı, reklamverenlere Birleşik Krallık'taki Türkçe konuşan kitlelere ulaşmak için güçlü bir kanal sunar.",
      disclaimer: "Rakamlar yakın dönem Instagram hesap istatistiklerine dayanır ve kampanya dönemine göre değişebilir.",
      items: turkishInsights
    },
    packages: {
      eyebrow: "Reklam paketleri",
      title: "Kampanyanıza uygun görünürlük seviyesini seçin",
      text: "Lansmanlar, etkinlikler, hizmetler, kampanyalar ve uzun vadeli marka bilinirliği için sade Instagram reklam seçenekleri.",
      bestForLabel: "En uygun:",
      buyCta: "Paketi Al",
      items: [
        {
          name: "Sadece Story Paketi",
          price: "£250",
          bestFor: "Hızlı duyurular, etkinlik hatırlatmaları ve link yönlendirmeleri",
          features: [
            "5 Instagram Story",
            "Uygun olduğunda link sticker",
            "Hesap etiketi",
            "Kısa vadeli görünürlük için ideal",
            "Instagram DM ile rezervasyon"
          ]
        },
        {
          name: "Başlangıç Paketi",
          price: "£300",
          bestFor: "İlk kez reklam verenler ve küçük işletmeler",
          features: [
            "1 Instagram gönderisi veya Reel",
            "2 Instagram Story",
            "Hesap etiketi",
            "Kampanya CTA desteği",
            "Instagram DM ile rezervasyon"
          ]
        },
        {
          name: "Standart Paket",
          price: "£450",
          bestFor: "Tek kampanya tanıtımı",
          features: [
            "1 Instagram gönderisi veya Reel",
            "3 Instagram Story",
            "3 gün sabitlenmiş gönderi",
            "3 gün profil linki yerleşimi",
            "Temel performans özeti",
            "Instagram DM ile rezervasyon"
          ]
        },
        {
          name: "Avantaj Paketi",
          price: "£600",
          label: "En Popüler",
          bestFor: "Daha güçlü görünürlük isteyen işletmeler",
          features: [
            "2 Instagram gönderisi veya Reel",
            "4 Instagram Story",
            "7 gün sabitlenmiş gönderi",
            "7 gün profil linki yerleşimi",
            "Uygun olduğunda diğer BritishTurks platformlarında çapraz paylaşım",
            "Temel kampanya performans özeti",
            "Instagram DM ile rezervasyon"
          ]
        },
        {
          name: "Pro Destek Paketi",
          price: "£800",
          bestFor: "Kampanya desteğine ihtiyaç duyan markalar",
          features: [
            "2 Instagram gönderisi veya Reel",
            "5 Instagram Story",
            "Kampanya stratejisi desteği",
            "Metin ve CTA optimizasyonu",
            "Topluluk etkileşimi desteği",
            "7 gün profil linki yerleşimi",
            "Temel performans özeti",
            "Instagram DM ile rezervasyon"
          ]
        },
        {
          name: "Premium Video Davet Paketi",
          price: "£1,250'den başlayan",
          bestFor: "Restoranlar, etkinlikler, klinikler, hizmetler ve işletme lansmanları",
          features: [
            "Tanıtım videosu veya röportaj tarzı çekim",
            "Kurgulanmış Instagram Reel",
            "3 Instagram Story",
            "Sabitlenmiş gönderi",
            "Profil linki yerleşimi",
            "Uygun olduğunda çapraz platform paylaşımı",
            "Fiyat lokasyon, çekim süresi ve kurgu ihtiyacına göre değişebilir",
            "Instagram DM ile rezervasyon"
          ]
        }
      ]
    },
    custom: {
      eyebrow: "Özel kampanyalar",
      title: "Aylık kampanyaya mı ihtiyacınız var?",
      text:
        "Uzun vadeli görünürlük, restoran lansmanları, etkinlikler, klinikler, hukuk hizmetleri, emlak danışmanları veya marka iş birlikleri için özel bir aylık kampanya oluşturabiliriz.",
      cta: "Instagram'da konuşalım"
    },
    why: {
      eyebrow: "Neden BritishTurks?",
      title: "BritishTurks ile neden reklam vermelisiniz?",
      text: "Kitle uyumu, kültürel yakınlık ve güçlü Instagram erişimi isteyen markalar için güvenilir bir medya platformu.",
      points: [
        "Güvenilir UK Türk toplumu platformu",
        "Güçlü Instagram Reels performansı",
        "Yüksek takipçi dışı erişim",
        "Topluluk odaklı içerik",
        "Birleşik Krallık'taki Türkçe konuşan kitleleri hedefleyen markalar için ideal",
        "Etkinlikler, restoranlar, klinikler, hukuk hizmetleri, seyahat, finans, emlak ve yerel işletmeler için uygun"
      ]
    },
    disclosure: {
      prefix: "Reklam açıklaması: ",
      text:
        "Tüm sponsorlu içerikler UK reklam yönergelerine uygun şekilde açıkça belirtilecektir. BritishTurks satış, potansiyel müşteri veya belirli sonuç garantisi vermez. Kampanya performansı içerik, zamanlama, kitle ilgisi ve platform algoritmalarına göre değişebilir."
    },
    faq: {
      eyebrow: "SSS",
      title: "Rezervasyon öncesi sık sorulan sorular",
      items: [
        {
          question: "Online ödeme yapıyor muyum?",
          answer:
            "Hayır. Uygunluk, kampanya detayları ve ödeme seçeneklerini konuşmak için lütfen Instagram DM üzerinden iletişime geçin."
        },
        {
          question: "Satış garantisi veriyor musunuz?",
          answer:
            "Hayır. Satış veya potansiyel müşteri garantisi vermiyoruz. Paketlerimiz, UK Türk toplumu içinde marka görünürlüğünü ve erişimi artırmak için tasarlanmıştır."
        },
        {
          question: "Paylaşım tarihini seçebilir miyim?",
          answer: "Evet, uygunluk ve editoryal takvime bağlıdır."
        },
        {
          question: "İçeriği bizim için hazırlayabilir misiniz?",
          answer:
            "Evet. Metin, CTA dili ve seçili kampanya formatlarında destek olabiliriz. Video prodüksiyonu Premium Video Davet Paketi kapsamında sunulur."
        },
        {
          question: "Paylaşım sponsorlu olarak işaretlenecek mi?",
          answer: "Evet. Sponsorlu içerikler UK reklam yönergelerine uygun şekilde açıkça belirtilecektir."
        }
      ]
    },
    sticky: {
      text: "Markanızı Birleşik Krallık Türk toplumuna tanıtmaya hazır mısınız?",
      cta: "Instagram'dan DM gönder"
    },
    footer: {
      brand: "BritishTurks",
      description: "Birleşik Krallık Türk Toplumu Medya Platformu",
      instagram: "Instagram: @britishturks",
      cta: "Instagram'dan DM gönder"
    }
  }
};
